[package]
name = "ts-to-avro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.189"
serde_json = "1.0.107"
tree-sitter = "0.20.10"
tree-sitter-typescript = "0.20.3"
